import { describe, expect, it } from 'vitest';

import { atr, bollinger, ema, macd, rsi, sma } from './indicators';
import type { Bar } from './types';
import fixture from './__fixtures__/engine-parity.json';

/**
 * Parity with the Python engine.
 *
 * The chart and the backtest must agree to the last decimal. If they drift,
 * a user sees one thing on screen and a different number in their results —
 * and has no way to tell which is right. The fixture is generated by
 * `packages/engine` and checked in, so a change to either side that breaks
 * agreement fails here.
 */

const TOLERANCE = 1e-9;

function compare(actual: Array<number | null>, expected: Array<number | null>, name: string) {
  expect(actual, `${name}: length`).toHaveLength(expected.length);

  for (let i = 0; i < expected.length; i += 1) {
    const want = expected[i];
    const got = actual[i];

    if (want === null) {
      expect(got, `${name}[${i}] should be null (warm-up)`).toBeNull();
      continue;
    }
    expect(got, `${name}[${i}] should have a value`).not.toBeNull();
    expect(got as number, `${name}[${i}]`).toBeCloseTo(want, 9);
  }
}

describe('parity with the Python engine', () => {
  const values = fixture.values as number[];
  const bars: Bar[] = values.map((close, i) => ({
    time: 1_700_000_000_000 + i * 60_000,
    open: close,
    high: close + 1,
    low: close - 1,
    close,
    volume: 1,
    closed: true,
  }));

  it('SMA(20) matches', () => {
    compare(sma(values, 20), fixture.sma20, 'sma20');
  });

  it('EMA(20) matches, including the SMA seed', () => {
    compare(ema(values, 20), fixture.ema20, 'ema20');
  });

  it('RSI(14) matches, including Wilder smoothing', () => {
    compare(rsi(values, 14), fixture.rsi14, 'rsi14');
  });

  it('MACD line matches', () => {
    compare(macd(values).macd, fixture.macd, 'macd');
  });

  it('MACD signal matches, including where the EMA of the line starts', () => {
    compare(macd(values).signal, fixture.macd_signal, 'macd_signal');
  });

  it('Bollinger upper band matches, including population stdev', () => {
    compare(bollinger(values, 20).upper, fixture.bb_upper, 'bb_upper');
  });

  it('ATR(14) matches', () => {
    compare(atr(bars, 14), fixture.atr14, 'atr14');
  });

  it('the fixture is substantial enough to catch drift', () => {
    expect(values.length).toBeGreaterThanOrEqual(100);
    expect(TOLERANCE).toBeLessThan(1e-6);
  });
});
