"""Phase 5: wireguard tunnels and feature routes

Revision ID: 0134a45b7fe8
Revises: bb288b222914
Create Date: 2026-09-26 08:35:58.015130
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0134a45b7fe8"
down_revision: str | None = "bb288b222914"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_routes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("feature", sa.String(length=32), nullable=False),
        sa.Column("tunnel_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_feature_routes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_routes")),
    )
    op.create_index(
        "ix_feature_routes_user_feature", "feature_routes", ["user_id", "feature"], unique=False
    )
    op.create_table(
        "tunnels",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("secret", sa.Text(), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tunnels_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tunnels")),
    )
    op.create_index("ix_tunnels_user_enabled", "tunnels", ["user_id", "enabled"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_feature_routes_user_feature", table_name="feature_routes")
    op.drop_table("feature_routes")
    op.drop_index("ix_tunnels_user_enabled", table_name="tunnels")
    op.drop_table("tunnels")
