"""phase 6 exchange keys, bots, bot orders

Revision ID: 381b6755b788
Revises: 0134a45b7fe8
Create Date: 2026-09-26 20:31:10.613630
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "381b6755b788"
down_revision: str | None = "0134a45b7fe8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_keys",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("api_key_sealed", sa.LargeBinary(), nullable=False),
        sa.Column("api_key_wrapped_key", sa.LargeBinary(), nullable=False),
        sa.Column("api_secret_sealed", sa.LargeBinary(), nullable=False),
        sa.Column("api_secret_wrapped_key", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.String(length=32), nullable=False),
        sa.Column("last_four", sa.String(length=8), nullable=False),
        sa.Column("fingerprint", sa.String(length=32), nullable=False),
        sa.Column("can_trade", sa.Boolean(), nullable=False),
        sa.Column("ip_whitelist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exchange_keys_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_keys")),
        sa.UniqueConstraint("user_id", "exchange", "label", name="uq_exchange_keys_label"),
    )
    op.create_index("ix_exchange_keys_user", "exchange_keys", ["user_id"], unique=False)
    op.create_table(
        "bots",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("setup_id", sa.UUID(), nullable=False),
        sa.Column("exchange_key_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("halt_reason", sa.String(length=32), nullable=True),
        sa.Column("halt_detail", sa.String(length=400), nullable=True),
        sa.Column("halted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("margin_mode", sa.String(length=16), nullable=False),
        sa.Column("position_mode", sa.String(length=16), nullable=False),
        sa.Column("max_position_notional", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_daily_loss", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_drawdown_percent", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_leverage", sa.Integer(), nullable=False),
        sa.Column("max_orders_per_minute", sa.Integer(), nullable=False),
        sa.Column("day_start_equity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("peak_equity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("day_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("equity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("armed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_signal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_key_id"],
            ["exchange_keys.id"],
            name=op.f("fk_bots_exchange_key_id_exchange_keys"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["setup_id"], ["setups.id"], name=op.f("fk_bots_setup_id_setups"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bots_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bots")),
    )
    op.create_index("ix_bots_user_state", "bots", ["user_id", "state"], unique=False)
    op.create_table(
        "bot_orders",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=40), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=64), nullable=True),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("filled_qty", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("average_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("fee", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("reduce_only", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=True),
        sa.Column("bar_time", sa.BigInteger(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=400), nullable=True),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_bot_orders_bot_id_bots"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_orders")),
        sa.UniqueConstraint("bot_id", "client_id", name="uq_bot_orders_client_id"),
    )
    op.create_index("ix_bot_orders_bot_sent", "bot_orders", ["bot_id", "sent_at"], unique=False)
    # Not noise: the phase 4 migrations for these two tables created the
    # timestamp columns without the server defaults their models declare,
    # so every autogenerate since has re-reported the difference. Applying
    # it here makes the database match the models and `alembic check`
    # clean, instead of carrying the divergence forward again.
    op.alter_column(
        "compute_preferences",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "compute_preferences",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bot_orders_bot_sent", table_name="bot_orders")
    op.drop_table("bot_orders")
    op.drop_index("ix_bots_user_state", table_name="bots")
    op.drop_table("bots")
    op.drop_index("ix_exchange_keys_user", table_name="exchange_keys")
    op.drop_table("exchange_keys")
    op.alter_column(
        "compute_preferences",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "compute_preferences",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
