"""phase 1: market data tables

Revision ID: ab7f57e86a2f
Revises: c1d370331017
Create Date: 2026-09-25 22:17:55.532898
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ab7f57e86a2f"
down_revision: str | None = "c1d370331017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backfill_state",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("price_type", sa.String(length=8), nullable=False),
        sa.Column("earliest_open_time", sa.BigInteger(), nullable=True),
        sa.Column("latest_open_time", sa.BigInteger(), nullable=True),
        sa.Column("bar_count", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", "interval", "price_type", name="pk_backfill_state"),
    )
    op.create_table(
        "funding_rates",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("funding_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("funding_rate", sa.Numeric(precision=20, scale=12), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "funding_time", name="pk_funding_rates"),
    )
    op.create_table(
        "instruments",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("base", sa.String(length=16), nullable=False),
        sa.Column("quote", sa.String(length=16), nullable=False),
        sa.Column("min_leverage", sa.Integer(), nullable=False),
        sa.Column("max_leverage", sa.Integer(), nullable=False),
        sa.Column("default_leverage", sa.Integer(), nullable=False),
        sa.Column("base_precision", sa.Integer(), nullable=False),
        sa.Column("quote_precision", sa.Integer(), nullable=False),
        sa.Column("min_trade_volume", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("api_supported", sa.Boolean(), nullable=False),
        sa.Column(
            "refreshed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_instruments")),
    )
    op.create_table(
        "klines",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("price_type", sa.String(length=8), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("high", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("low", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("close", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("volume", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("quote_volume", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", "interval", "price_type", "open_time", name="pk_klines"),
    )
    op.create_index(
        "ix_klines_lookup",
        "klines",
        ["symbol", "interval", "price_type", "open_time"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- TimescaleDB ----------------------------------------------------
    # klines and funding_rates are append-mostly time series. Chunking them
    # keeps range scans on the chart's visible window off the whole table,
    # and lets old chunks be compressed later without touching queries.
    op.execute(
        "SELECT create_hypertable('klines', 'open_time', "
        "chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE, "
        "migrate_data => TRUE)"
    )
    op.execute(
        "SELECT create_hypertable('funding_rates', 'funding_time', "
        "chunk_time_interval => INTERVAL '90 days', if_not_exists => TRUE, "
        "migrate_data => TRUE)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_klines_lookup", table_name="klines")
    op.drop_table("klines")
    op.drop_table("instruments")
    op.drop_table("funding_rates")
    op.drop_table("backfill_state")
    # ### end Alembic commands ###
