"""Phase 5: paper trading sessions and fills

Revision ID: bb288b222914
Revises: 45c5c7431785
Create Date: 2026-09-26 08:22:18.800541
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "bb288b222914"
down_revision: str | None = "45c5c7431785"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("setup_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("initial_capital", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("equity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("expected_net_percent", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("expected_low_percent", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("expected_high_percent", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("drawdown_limit_percent", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("missed_signals", sa.Integer(), nullable=False),
        sa.Column("last_bar_time", sa.Integer(), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_by_override", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["setup_id"],
            ["setups.id"],
            name=op.f("fk_paper_sessions_setup_id_setups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_paper_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_sessions")),
    )
    op.create_index(
        "ix_paper_sessions_user_state", "paper_sessions", ["user_id", "state"], unique=False
    )
    op.create_table(
        "paper_fills",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("bar_time", sa.Integer(), nullable=False),
        sa.Column("signal_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("fill_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("fee", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("funding", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("net_pnl", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("equity_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
            name=op.f("fk_paper_fills_session_id_paper_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_fills")),
    )
    op.create_index(
        "ix_paper_fills_session_time", "paper_fills", ["session_id", "filled_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_paper_fills_session_time", table_name="paper_fills")
    op.drop_table("paper_fills")
    op.drop_index("ix_paper_sessions_user_state", table_name="paper_sessions")
    op.drop_table("paper_sessions")
