"""refresh token rotation grace window

Revision ID: c1d370331017
Revises: f346f8f7f470
Create Date: 2026-09-25 22:03:54.947453
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c1d370331017"
down_revision: str | None = "f346f8f7f470"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_sessions", sa.Column("previous_token_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "auth_sessions", sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_auth_sessions_previous_token_hash"),
        "auth_sessions",
        ["previous_token_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_sessions_previous_token_hash"), table_name="auth_sessions")
    op.drop_column("auth_sessions", "rotated_at")
    op.drop_column("auth_sessions", "previous_token_hash")
    # ### end Alembic commands ###
